### ISSUE TITLE
Add blog post list to public profile

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#311]
Example:

![screencapture-localhost-8000-fellow-black-widow-1492688778893](https://cloud.githubusercontent.com/assets/1506457/25229310/a1471234-25c7-11e7-9a48-9177006c1465.png)

Things to include in the list

- [x] Blog posts wrote by the fellow
- [x] Blog post co-wrote by the fellow
- [ ] Link to more if the fellow has a personal blog

**Comment by rgaiacs** [comment]
Probably better to ask fellows.

**Comment by rgaiacs** [comment]
# Public profile

![screencapture-localhost-8000-fellow-captain-america-1496849673963](https://user-images.githubusercontent.com/1506457/26887205-4af80566-4b9f-11e7-88a5-d5cd9491471c.png)

![screencapture-localhost-8000-fellow-iron-man-1496849911675](https://user-images.githubusercontent.com/1506457/26887375-c77c1410-4b9f-11e7-84df-3e0f09e03fdd.png)

# When looking your own profile

![screencapture-localhost-8000-fellow-captain-america-1496849758625](https://user-images.githubusercontent.com/1506457/26887272-7bb9011e-4b9f-11e7-8cbb-675550238adf.png)

User has access to a little more of information. **Side effect is that users will also have extra information when looking on other fellows profile.**

![screencapture-localhost-8000-fellow-iron-man-1496849898430](https://user-images.githubusercontent.com/1506457/26887430-ebe09ad8-4b9f-11e7-912a-e76950e4f09f.png)

# Staff

![screencapture-localhost-8000-fellow-captain-america-1496850013211](https://user-images.githubusercontent.com/1506457/26887475-06f96c78-4ba0-11e7-81fe-325a7861a165.png)

![screencapture-localhost-8000-fellow-iron-man-1496850021214](https://user-images.githubusercontent.com/1506457/26887484-0b15e8b8-4ba0-11e7-9010-2751bc6337d5.png)

Staffs have extra information since the profile is used as a shortcut to fellows information.
 
# TODO

Need to fix the issue before merge the pull request.

**Comment by rgaiacs** [comment]
The issue mentioned before was fixed with fefa79b.
