### ISSUE TITLE
Update requirements for compatibility with latest Django

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#413]
This is the list of requirements at the moment related with Django

- [ ] django-backup
- [x] django-constance[database]
- [ ] django-countries
- [x] django-crispy-forms
- [ ] django-datetime-widget
- [ ] django-dbbackup
- [x] django-extensions
- [ ] django-settings-export
- [ ] django-simple-history, blocked by https://github.com/treyhunner/django-simple-history/pull/320 and https://github.com/treyhunner/django-simple-history/pull/340
- [ ] pylint
- [x] pylint-django
- [ ] django-autofixture

They need to be compatible with Django 2.0 for us to migrate.

**Comment by rgaiacs** [comment]
From https://docs.djangoproject.com/en/2.0/faq/install/#what-python-version-can-i-use-with-django

> What Python version can I use with Django?
>
> Django version: 1.11 Python versions: 2.7, 3.4, 3.5, 3.6
> Django version: 2.0 Python versions: 3.4, 3.5, 3.6
> Django version: 2.1 Python versions: 3.5, 3.6, 3.7

**Comment by shoaibsufi** [comment]
which Django version does lowFAT use at the moment?

**Comment by rgaiacs** [comment]
1.11 which will be supported until at least April 2020

**Comment by jag1g13** [comment]
Version 2.2 is the next LTS release (was released a couple of months ago) so we should skip straight there when we do upgrade.  I'll check off the list here as dependencies are upgraded to 2.2

- [ ] django-backup
- [ ] django-constance[database]
- [ ] django-countries
- [ ] django-crispy-forms
- [ ] django-datetime-widget
- [ ] django-dbbackup
- [ ] django-extensions
- [ ] django-settings-export
- [ ] django-simple-history, blocked by treyhunner/django-simple-history#320 and treyhunner/django-simple-history#340
- [ ] pylint
- [ ] pylint-django
- [ ] django-autofixture

**Comment by PipGrylls** [comment]
Update

- [ ]  django-constance[database]
- [ ]  django-countries
- [X]  django-crispy-forms
- [X]  django-datetime-widget
- [ ]  django-dbbackup
- [X]  django-extensions
- [ ]  django-settings-export
- [ ]  django-simple-history, blocked by jazzband/django-simple-history#320 and jazzband/django-simple-history#340
- [X]  pylint-django
- [ ]  django-autofixture
- [ ] django v4 deprcation warnings
- [ ] django v3.2 test warnings

**Comment by PipGrylls** [comment]
- [X]  django-countries
Support for 3.2 and active development

**Comment by PipGrylls** [comment]
- [X]  django-dbbackup
Support for 3.2 and active development.
Also note: #624, that restoring from backup can trigger this issue. Until it is fixed downgrading to dj-v3.1 restoring the backup and then going back to 3.2 is a woraround.

**Comment by PipGrylls** [comment]
- [X]  django-settings-export
 No versions since 2016 but active PR that indicate updates are ongoing and 3.2 support

**Comment by PipGrylls** [comment]
- [X]  django-simple-history, blocked by jazzband/django-simple-history#320 and jazzband/django-simple-history#340
Support for 3.2 and active development. And issues mentioned closed.

**Comment by PipGrylls** [comment]
- [X] django-autofixture
There seem to be no uses in the code so this is removed from requirements.
It is also unsupported outside of dj-v1.4-9

**Comment by PipGrylls** [comment]
- [X] django v3.2 test warnings
Fixed by adding ```DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'```

**Comment by PipGrylls** [comment]
Update

- [X]  django-constance[database]
- [X]  django-countries
- [X]  django-crispy-forms
- [X]  django-datetime-widget
- [X]  django-dbbackup (Slight issue see #624)
- [X]  django-extensions
- [X]  django-settings-export
- [X]  django-simple-history
- [X]  pylint-django
- [X]  django-autofixture (REMOVED)
- [ ]  django v4 deprcation warnings
- [X]  django v3.2 test warnings

**Comment by PipGrylls** [comment]
Closing this moving this last issue to #626

- [ ] django v4 deprcation warnings
This issue comes from the dependencies:

- constance
- dbbackup
- social_django
- tagulous
- imagekit

it is unclear where this error is coming from:
```RemovedInDjango40Warning: The {% ifnotequal %} template tag is deprecated in favor of {% if %}. [defaulttags.py:872]```
