### ISSUE TITLE
[Meta] GDPR compatibility

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#417]
- [ ] [right to erasure](https://github.com/softwaresaved/lowfat/issues/458)
- [ ] [right to restriction of processing](https://github.com/softwaresaved/lowfat/issues/459)
- [ ] [right to data portability](https://github.com/softwaresaved/lowfat/issues/460)
- [ ] [right to rectification](https://github.com/softwaresaved/lowfat/issues/461)
- [ ] [right to be informed](https://github.com/softwaresaved/lowfat/issues/462)
- [ ] [right of access](https://github.com/softwaresaved/lowfat/issues/463)
