### ISSUE TITLE
[GDPR] Right to data portability

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#460]
Users can't export their data in a machine-readable format.

# TODO

- [ ] Established the machine-readable format that will be used. Probably JSON.
- [ ] Create a procedure to receive users requests.
- [ ] Create a page with the procedure.
