### ISSUE TITLE
Lowfat maintainance & development

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#761]
# Q2 Apr-Jun 
 
 - [ ] sprint on 4 April
 - [ ] scraper.software.ac.uk
  - [ ] SSH access
  - [ ] test server
  - [ ] install Django on scraper VM
  - [ ] documentation
- [ ] upgrade to Django 5
  - [ ] test switch on/off fellows VM
  - [ ] Philly upgrades to Django
  - [ ] test everything is working
- [ ] fellows.software.ac.uk
  - [ ] SSH access
  - [ ] get confirmation from EPCC about dates for 
  - [ ] migration of OS
  - [ ] documentation
- [ ] create a stakeholders map
  - [ ] definition of lowFAT stakeholders groups
  - [ ] process of engagement
  - [ ] plan collection of feed-back from fellows
# Q3 Jul - Sep
- review lowFAT features, ensure it fits stakeholders needs 
- review current issues
- triage/prioritize issues
- scope out if there is room for a new release of lowFAT
# Q4 Oct - Dec 
- [ ] uConfly (see [notes](https://docs.google.com/document/d/1edSUVE6ZkHTH6RoIxkcdjJdniYT76-G__dtxhjOV55A/edit#heading=h.jw605csfsvl2) )

**Comment by gperu** [comment]
See https://github.com/softwaresaved/InstituteIssues/issues/392
